import unittest
import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import Select

class TestPrintTranscript(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Chrome()
        self.driver.maximize_window()
        self.driver.get("https://mybk.hcmut.edu.vn/my/logoutSSO.action")
        self.driver.get('https://sso.hcmut.edu.vn/cas/login?service=https://mybk.hcmut.edu.vn/my/homeSSO.action')
        username = self.driver.find_element(By.NAME,"username")
        password = self.driver.find_element(By.NAME,"password")  
        submitBtn = self.driver.find_element(By.NAME,"submit")  
        
        username.send_keys("phu.hahaphanthienphultt")
        password.send_keys("123456789@")
        submitBtn.click()
  

    def get_element_wait(self, element_id, timeout=3):
        try:
            return WebDriverWait(self.driver, timeout).until(
                EC.presence_of_element_located((By.ID, element_id))
            )
        except TimeoutException:
            err = 'Element with id {} could not be found!'
            raise Exception(err.format(element_id))

    def test_1(self): #done
        self.driver.get("https://mybk.hcmut.edu.vn/apps/src/nopccav/index.aspx")
        self.driver.find_element(By.XPATH,'//*[@id="bnt_themmoi"]').click()
        time.sleep(2)
        selectType =Select(self.driver.find_element(By.ID,'cbo_loaicc'))
        selectType.select_by_value("TOEIC_1")
        time.sleep(2)
        id = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_IdNumber")
        date = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TestDate")  
        listeningInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Listening")
        readingInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Reading")
        total = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TotalScore")
        id.send_keys("1111111111")
        date.send_keys("23/11/2022")
        readingInp.send_keys(-1)
        listeningInp.send_keys(250)
        total.send_keys(249)
        btn = self.driver.find_element(By.XPATH,'//*[@id="bnt_thoinhap"]')
        time.sleep(2)
        btn.click()
        time.sleep(2)
        assert self.driver.find_element(By.XPATH,'//*[@id="lst_danhsachccnn"]')
    

    def test_2(self): #done
        self.driver.get("https://mybk.hcmut.edu.vn/apps/src/nopccav/index.aspx")
        self.driver.find_element(By.XPATH,'//*[@id="bnt_themmoi"]').click()
        time.sleep(2)
        selectType =Select(self.driver.find_element(By.ID,'cbo_loaicc'))
        selectType.select_by_value("TOEIC_1")
        time.sleep(2)
        id = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_IdNumber")
        date = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TestDate")  
        listeningInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Listening")
        readingInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Reading")
        total = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TotalScore")
        id.send_keys("1111111111")
        date.send_keys("23/11/2022")
        readingInp.send_keys(0)
        listeningInp.send_keys(250)
        total.send_keys(250)
        btn = self.driver.find_element(By.XPATH,'//*[@id="bnt_thoinhap"]')
        time.sleep(2)
        btn.click()
        time.sleep(2)
        assert self.driver.find_element(By.XPATH,'//*[@id="lst_danhsachccnn"]')

    def test_3(self): #done
        self.driver.get("https://mybk.hcmut.edu.vn/apps/src/nopccav/index.aspx")
        self.driver.find_element(By.XPATH,'//*[@id="bnt_themmoi"]').click()
        time.sleep(2)
        selectType =Select(self.driver.find_element(By.ID,'cbo_loaicc'))
        selectType.select_by_value("TOEIC_1")
        time.sleep(2)
        id = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_IdNumber")
        date = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TestDate")  
        listeningInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Listening")
        readingInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Reading")
        total = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TotalScore")
        id.send_keys("1111111111")
        date.send_keys("23/11/2022")
        readingInp.send_keys(1)
        listeningInp.send_keys(250)
        total.send_keys(251)
        btn = self.driver.find_element(By.XPATH,'//*[@id="bnt_thoinhap"]')
        time.sleep(2)
        btn.click()
        time.sleep(2)
        assert self.driver.find_element(By.XPATH,'//*[@id="lst_danhsachccnn"]')

    def test_4(self): #done
        self.driver.get("https://mybk.hcmut.edu.vn/apps/src/nopccav/index.aspx")
        self.driver.find_element(By.XPATH,'//*[@id="bnt_themmoi"]').click()
        time.sleep(2)
        selectType =Select(self.driver.find_element(By.ID,'cbo_loaicc'))
        selectType.select_by_value("TOEIC_1")
        time.sleep(2)
        id = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_IdNumber")
        date = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TestDate")  
        listeningInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Listening")
        readingInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Reading")
        total = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TotalScore")
        id.send_keys("1111111111")
        date.send_keys("23/11/2022")
        readingInp.send_keys(250)
        listeningInp.send_keys(-1)
        total.send_keys(249)
        btn = self.driver.find_element(By.XPATH,'//*[@id="bnt_thoinhap"]')
        time.sleep(2)
        btn.click()
        time.sleep(2)
        assert self.driver.find_element(By.XPATH,'//*[@id="lst_danhsachccnn"]')

    def test_5(self): #done
        self.driver.get("https://mybk.hcmut.edu.vn/apps/src/nopccav/index.aspx")
        self.driver.find_element(By.XPATH,'//*[@id="bnt_themmoi"]').click()
        time.sleep(2)
        selectType =Select(self.driver.find_element(By.ID,'cbo_loaicc'))
        selectType.select_by_value("TOEIC_1")
        time.sleep(2)
        id = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_IdNumber")
        date = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TestDate")  
        listeningInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Listening")
        readingInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Reading")
        total = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TotalScore")
        id.send_keys("1111111111")
        date.send_keys("23/11/2022")
        readingInp.send_keys(250)
        listeningInp.send_keys(0)
        total.send_keys(250)
        btn = self.driver.find_element(By.XPATH,'//*[@id="bnt_thoinhap"]')
        time.sleep(2)
        btn.click()
        time.sleep(2)
        assert self.driver.find_element(By.XPATH,'//*[@id="lst_danhsachccnn"]')

    def test_6(self): #done
        self.driver.get("https://mybk.hcmut.edu.vn/apps/src/nopccav/index.aspx")
        self.driver.find_element(By.XPATH,'//*[@id="bnt_themmoi"]').click()
        time.sleep(2)
        selectType =Select(self.driver.find_element(By.ID,'cbo_loaicc'))
        selectType.select_by_value("TOEIC_1")
        time.sleep(2)
        id = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_IdNumber")
        date = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TestDate")  
        listeningInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Listening")
        readingInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Reading")
        total = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TotalScore")
        id.send_keys("1111111111")
        date.send_keys("23/11/2022")
        readingInp.send_keys(250)
        listeningInp.send_keys(1)
        total.send_keys(251)
        btn = self.driver.find_element(By.XPATH,'//*[@id="bnt_thoinhap"]')
        time.sleep(2)
        btn.click()
        time.sleep(2)
        assert self.driver.find_element(By.XPATH,'//*[@id="lst_danhsachccnn"]')

    def test_7(self): #done
        self.driver.get("https://mybk.hcmut.edu.vn/apps/src/nopccav/index.aspx")
        self.driver.find_element(By.XPATH,'//*[@id="bnt_themmoi"]').click()
        time.sleep(2)
        selectType =Select(self.driver.find_element(By.ID,'cbo_loaicc'))
        selectType.select_by_value("TOEIC_1")
        time.sleep(2)
        id = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_IdNumber")
        date = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TestDate")  
        listeningInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Listening")
        readingInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Reading")
        total = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TotalScore")
        id.send_keys("1111111111")
        date.send_keys("23/11/2022")
        readingInp.send_keys(250)
        listeningInp.send_keys(494)
        total.send_keys(744)
        btn = self.driver.find_element(By.XPATH,'//*[@id="bnt_thoinhap"]')
        time.sleep(2)
        btn.click()
        time.sleep(2)
        assert self.driver.find_element(By.XPATH,'//*[@id="lst_danhsachccnn"]')

    def test_8(self): #done
        self.driver.get("https://mybk.hcmut.edu.vn/apps/src/nopccav/index.aspx")
        self.driver.find_element(By.XPATH,'//*[@id="bnt_themmoi"]').click()
        time.sleep(2)
        selectType =Select(self.driver.find_element(By.ID,'cbo_loaicc'))
        selectType.select_by_value("TOEIC_1")
        time.sleep(2)
        id = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_IdNumber")
        date = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TestDate")  
        listeningInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Listening")
        readingInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Reading")
        total = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TotalScore")
        id.send_keys("1111111111")
        date.send_keys("23/11/2022")
        readingInp.send_keys(250)
        listeningInp.send_keys(495)
        total.send_keys(745)
        btn = self.driver.find_element(By.XPATH,'//*[@id="bnt_thoinhap"]')
        time.sleep(2)
        btn.click()
        time.sleep(2)
        assert self.driver.find_element(By.XPATH,'//*[@id="lst_danhsachccnn"]')

    def test_9(self): #done
        self.driver.get("https://mybk.hcmut.edu.vn/apps/src/nopccav/index.aspx")
        self.driver.find_element(By.XPATH,'//*[@id="bnt_themmoi"]').click()
        time.sleep(2)
        selectType =Select(self.driver.find_element(By.ID,'cbo_loaicc'))
        selectType.select_by_value("TOEIC_1")
        time.sleep(2)
        id = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_IdNumber")
        date = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TestDate")  
        listeningInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Listening")
        readingInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Reading")
        total = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TotalScore")
        id.send_keys("1111111111")
        date.send_keys("23/11/2022")
        readingInp.send_keys(250)
        listeningInp.send_keys(496)
        total.send_keys(746)
        btn = self.driver.find_element(By.XPATH,'//*[@id="bnt_thoinhap"]')
        time.sleep(2)
        btn.click()
        time.sleep(2)
        assert self.driver.find_element(By.XPATH,'//*[@id="lst_danhsachccnn"]')

    def test_10(self): #done
        self.driver.get("https://mybk.hcmut.edu.vn/apps/src/nopccav/index.aspx")
        self.driver.find_element(By.XPATH,'//*[@id="bnt_themmoi"]').click()
        time.sleep(2)
        selectType =Select(self.driver.find_element(By.ID,'cbo_loaicc'))
        selectType.select_by_value("TOEIC_1")
        time.sleep(2)
        id = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_IdNumber")
        date = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TestDate")  
        listeningInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Listening")
        readingInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Reading")
        total = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TotalScore")
        id.send_keys("1111111111")
        date.send_keys("23/11/2022")
        readingInp.send_keys(494)
        listeningInp.send_keys(250)
        total.send_keys(744)
        btn = self.driver.find_element(By.XPATH,'//*[@id="bnt_thoinhap"]')
        time.sleep(2)
        btn.click()
        time.sleep(2)
        assert self.driver.find_element(By.XPATH,'//*[@id="lst_danhsachccnn"]')

    def test_11(self): #done
        self.driver.get("https://mybk.hcmut.edu.vn/apps/src/nopccav/index.aspx")
        self.driver.find_element(By.XPATH,'//*[@id="bnt_themmoi"]').click()
        time.sleep(2)
        selectType =Select(self.driver.find_element(By.ID,'cbo_loaicc'))
        selectType.select_by_value("TOEIC_1")
        time.sleep(2)
        id = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_IdNumber")
        date = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TestDate")  
        listeningInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Listening")
        readingInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Reading")
        total = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TotalScore")
        id.send_keys("1111111111")
        date.send_keys("23/11/2022")
        readingInp.send_keys(495)
        listeningInp.send_keys(250)
        total.send_keys(745)
        btn = self.driver.find_element(By.XPATH,'//*[@id="bnt_thoinhap"]')
        time.sleep(2)
        btn.click()
        time.sleep(2)
        assert self.driver.find_element(By.XPATH,'//*[@id="lst_danhsachccnn"]')

    def test_12(self): #done
        self.driver.get("https://mybk.hcmut.edu.vn/apps/src/nopccav/index.aspx")
        self.driver.find_element(By.XPATH,'//*[@id="bnt_themmoi"]').click()
        time.sleep(2)
        selectType =Select(self.driver.find_element(By.ID,'cbo_loaicc'))
        selectType.select_by_value("TOEIC_1")
        time.sleep(2)
        id = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_IdNumber")
        date = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TestDate")  
        listeningInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Listening")
        readingInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Reading")
        total = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TotalScore")
        id.send_keys("1111111111")
        date.send_keys("23/11/2022")
        readingInp.send_keys(496)
        listeningInp.send_keys(250)
        total.send_keys(746)
        btn = self.driver.find_element(By.XPATH,'//*[@id="bnt_thoinhap"]')
        time.sleep(2)
        btn.click()
        time.sleep(2)
        assert self.driver.find_element(By.XPATH,'//*[@id="lst_danhsachccnn"]')

    def test_13(self): #done
        self.driver.get("https://mybk.hcmut.edu.vn/apps/src/nopccav/index.aspx")
        self.driver.find_element(By.XPATH,'//*[@id="bnt_themmoi"]').click()
        time.sleep(2)
        selectType =Select(self.driver.find_element(By.ID,'cbo_loaicc'))
        selectType.select_by_value("TOEIC_1")
        time.sleep(2)
        id = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_IdNumber")
        date = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TestDate")  
        listeningInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Listening")
        readingInp = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_Reading")
        total = self.driver.find_element(By.NAME,"ctl00$ContentPlaceHolder1$txt_TOEIC_TotalScore")
        id.send_keys("1111111111")
        date.send_keys("23/11/2022")
        readingInp.send_keys(250)
        listeningInp.send_keys(250)
        total.send_keys(250)
        btn = self.driver.find_element(By.XPATH,'//*[@id="bnt_thoinhap"]')
        time.sleep(2)
        btn.click()
        time.sleep(2)
        assert self.driver.find_element(By.XPATH,'//*[@id="lst_danhsachccnn"]')




    def tearDown(self):
        self.driver.get("https://mybk.hcmut.edu.vn/my/homeSSO.action")
        logoutBtn = self.driver.find_element(By.XPATH,"/html/body/div[2]/div/div/div[2]/div/a[1]")
        logoutBtn.click()
        self.driver.quit()


if __name__ == '__main__':
    unittest.main()