# Generated by Selenium IDE
import openpyxl
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from selenium.common.exceptions import NoSuchElementException

class FileExcelReader:
    file = ""
    sheetName = ""

    def __init__(self, file, sheetName):
        self.file = file
        self.sheetName = sheetName

    def getRowCount(self):
        wordbook = openpyxl.load_workbook(self.file)
        sheet = wordbook[self.sheetName]
        return (sheet.max_row)

    def getColumnCount(self):
        wordbook = openpyxl.load_workbook(self.file)
        sheet = wordbook[self.sheetName]
        return (sheet.max_column)

    def readData(self, rownum, colnum):
        wordbook = openpyxl.load_workbook(self.file)
        sheet = wordbook[self.sheetName]
        return sheet.cell(row=rownum, column=colnum).value

    def writeData(self, data, rownum, colnum):
        wordbook = openpyxl.load_workbook(self.file)
        sheet = wordbook[self.sheetName]
        sheet.cell(row=rownum, column=colnum).value = data
        wordbook.save(self.file)

class TestLogin():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.driver.maximize_window()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
#   def check_exists_by_xpath(xpath):
#     try:
#         webdriver.find_element_by_xpath(xpath)
#     except NoSuchElementException:
#         return False
#     return True

  def test_login(self, username, password, expectedResult):
    self.driver.get('http://localhost:8000/login.php')
    usernameInput = self.driver.find_element(By.NAME,"username")
    passwordInput = self.driver.find_element(By.NAME,"password")
    submitBtn = self.driver.find_element(By.NAME,"submit")
    if (username is not None):
        usernameInput.send_keys(username)
    if (password is not None):
        passwordInput.send_keys(password)    
    submitBtn.click()
    time.sleep(2)
    if expectedResult == "Success":
        assert self.driver.current_url == 'http://localhost:8000/index.php'
        logoutBtn = self.driver.find_element(By.XPATH,'//*[@id="mainNavbarCollapse"]/ul/li[4]/a')
        logoutBtn.click()
        return True
    else:        
        errorNotification = self.driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/span[1]')
        assert errorNotification.text == "Invalid Username or Password!"
        return True

        
    
  

if __name__ == "__main__":
    excel = FileExcelReader('SecA_login_data.xlsx', 'Sheet1')

    test = TestLogin()
    test.setup_method()
    nRows = excel.getRowCount()
    for row in range(2, nRows + 1):
        username = str(excel.readData(row,1))
        password = str(excel.readData(row,2))
        expectedResult = excel.readData(row,3)
        if username is None:
            username = ""
        if password is None:
            password = ""

        try:
            result = test.test_login(username, password, expectedResult)
            excel.writeData("Passed",row,4)
        except:
            excel.writeData("Failed",row,4)


    test.teardown_method()