# Generated by Selenium IDE
import openpyxl
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import Select

from selenium.common.exceptions import NoSuchElementException

class FileExcelReader:
    file = ""
    sheetName = ""

    def __init__(self, file, sheetName):
        self.file = file
        self.sheetName = sheetName

    def getRowCount(self):
        wordbook = openpyxl.load_workbook(self.file)
        sheet = wordbook[self.sheetName]
        return (sheet.max_row)

    def getColumnCount(self):
        wordbook = openpyxl.load_workbook(self.file)
        sheet = wordbook[self.sheetName]
        return (sheet.max_column)

    def readData(self, rownum, colnum):
        wordbook = openpyxl.load_workbook(self.file)
        sheet = wordbook[self.sheetName]
        return sheet.cell(row=rownum, column=colnum).value

    def writeData(self, data, rownum, colnum):
        wordbook = openpyxl.load_workbook(self.file)
        sheet = wordbook[self.sheetName]
        sheet.cell(row=rownum, column=colnum).value = data
        wordbook.save(self.file)

class TestRegAuth():
    def setup_method(self):
        self.driver = webdriver.Chrome()
        self.driver.maximize_window()
        self.vars = {}
        self.driver.get("https://mybk.hcmut.edu.vn/my/logoutSSO.action")
        self.driver.get('https://sso.hcmut.edu.vn/cas/login?service=https://mybk.hcmut.edu.vn/my/homeSSO.action')
        username = self.driver.find_element(By.NAME,"username")
        password = self.driver.find_element(By.NAME,"password")  
        submitBtn = self.driver.find_element(By.NAME,"submit")  
        
        username.send_keys("huy.dangquang")
        password.send_keys("0854001109")
        submitBtn.click()
  
    def teardown_method(self):
        self.driver.get("https://mybk.hcmut.edu.vn/my/homeSSO.action")
        logoutBtn = self.driver.find_element(By.XPATH,"/html/body/div[2]/div/div/div[2]/div/a[1]")
        logoutBtn.click()
        self.driver.quit()
  
  
    def test_regauth(self,flow,reason,address,expectedResult):
        self.driver.get('https://mybk.hcmut.edu.vn/app')
        self.driver.get('https://mybk.hcmut.edu.vn/app/sinh-vien/chung-nhan-sinh-vien/dang-ky')

        if flow == "Normal":
            reasonInput = self.driver.find_element(By.ID,'select2-cboLoaiDangKy-container')
            reasonInput.click()
            time.sleep(1)
            ForeginBtn = self.driver.find_element(By.XPATH,'//*[@id="select2-cboLoaiDangKy-results"]/li[3]')
            ForeginBtn.click()
            time.sleep(1)
            addressInput = self.driver.find_element(By.ID,'select2-cboNoiNhan-container')
            addressInput.click()
            time.sleep(1)
            Cs2btn = self.driver.find_element(By.XPATH,'/html/body/span/span/span[2]/ul/li[4]')
            Cs2btn.click()
            time.sleep(1)
            submitbtn = self.driver.find_element(By.XPATH,'/html/body/div[2]/div/section[2]/div/div/ul/li[3]/div/div[2]/button[1]')
            submitbtn.click()
            assert self.driver.find_element(By.XPATH,'//*[@id="lstPhieuDangChoXuLy"]/tbody/tr')
        
        elif flow =="NoReason":
            reasonInput = self.driver.find_element(By.ID,'select2-cboLoaiDangKy-container')
            time.sleep(1)
            addressInput = self.driver.find_element(By.ID,'select2-cboNoiNhan-container')
            addressInput.click()
            time.sleep(1)
            Cs1btn = self.driver.find_element(By.XPATH,'//*[@id="select2-cboNoiNhan-results"]/li[1]')
            Cs1btn.click()
            time.sleep(1)
            submitbtn = self.driver.find_element(By.XPATH,'/html/body/div[2]/div/section[2]/div/div/ul/li[3]/div/div[2]/button[1]')
            submitbtn.click()
            time.sleep(2)
            annoucement = self.driver.find_element(By.XPATH,'/html/body/div[4]/div/div[2]/div[1]')
            assert annoucement.text == "Bạn chưa chọn lý do đăng ký chứng nhận sinh viên"

        elif flow == "NoAddress":
            reasonInput = self.driver.find_element(By.ID,'select2-cboLoaiDangKy-container')
            reasonInput.click()
            time.sleep(1)
            ForeginBtn = self.driver.find_element(By.XPATH,'//*[@id="select2-cboLoaiDangKy-results"]/li[3]')
            ForeginBtn.click()
            time.sleep(1)
            submitbtn = self.driver.find_element(By.XPATH,'/html/body/div[2]/div/section[2]/div/div/ul/li[3]/div/div[2]/button[1]')
            submitbtn.click()
            time.sleep(2)
            annoucement = self.driver.find_element(By.XPATH,'//*[@id="swal2-content"]')
            assert annoucement.text == "Bạn chưa chọn nơi nhận kết quả"       
        
        elif flow == "ReSubmit":
            reasonInput = self.driver.find_element(By.ID,'select2-cboLoaiDangKy-container')
            reasonInput = self.driver.find_element(By.ID,'select2-cboLoaiDangKy-container')
            reasonInput.click()
            time.sleep(1)
            ForeginBtn = self.driver.find_element(By.XPATH,'//*[@id="select2-cboLoaiDangKy-results"]/li[3]')
            ForeginBtn.click()
            time.sleep(1)
            addressInput = self.driver.find_element(By.ID,'select2-cboNoiNhan-container')
            addressInput.click()
            time.sleep(1)
            Cs2btn = self.driver.find_element(By.XPATH,'/html/body/span/span/span[2]/ul/li[4]')
            Cs2btn.click()
            time.sleep(1)
            again = self.driver.find_element(By.XPATH,'//*[@id="btnNhapLai"]')
            again.click()
            time.sleep(1)
            reasonInput.click()
            time.sleep(1)
            ForeginBtn = self.driver.find_element(By.XPATH,'/html/body/span/span/span[2]/ul/li[6]')
            ForeginBtn.click()
            time.sleep(1)
            addressInput.click()
            time.sleep(1)
            Cs2btn = self.driver.find_element(By.XPATH,'//*[@id="select2-cboNoiNhan-results"]/li[2]')
            Cs2btn.click()
            time.sleep(1)
            submitbtn = self.driver.find_element(By.XPATH,'/html/body/div[2]/div/section[2]/div/div/ul/li[3]/div/div[2]/button[1]')
            submitbtn.click()
            time.sleep(2)
            assert self.driver.find_element(By.XPATH,'//*[@id="lstPhieuDangChoXuLy"]/tbody/tr')


        else:
            if (reason):
                reasonInput = self.driver.find_element(By.ID,'select2-cboLoaiDangKy-container')
                reasonInput.click()
                time.sleep(1)
                ToeicBtn = self.driver.find_element(By.XPATH,'/html/body/span/span/span[2]/ul/li[1]')
                ToeicBtn.click()
                time.sleep(1)
            if (address):
                addressInput = self.driver.find_element(By.ID,'select2-cboNoiNhan-container')
                addressInput.click()
                time.sleep(1)
                Cs2btn = self.driver.find_element(By.XPATH,'/html/body/span/span/span[2]/ul/li[4]')
                Cs2btn.click()
                time.sleep(1)
            submitbtn = self.driver.find_element(By.XPATH,'/html/body/div[2]/div/section[2]/div/div/ul/li[3]/div/div[2]/button[1]')
            submitbtn.click()
            time.sleep(2)
            if (expectedResult == "Success"):
                assert self.driver.find_element(By.XPATH,'//*[@id="lstPhieuDangChoXuLy"]/tbody/tr')
            elif (expectedResult == "NoRea"):
                annoucement = self.driver.find_element(By.XPATH,'/html/body/div[4]/div/div[2]/div[1]')
                assert annoucement.text == "Bạn chưa chọn lý do đăng ký chứng nhận sinh viên"
            else:
                annoucement = self.driver.find_element(By.XPATH,'//*[@id="swal2-content"]')
                assert annoucement.text == "Bạn chưa chọn nơi nhận kết quả"


  
if __name__ == "__main__":
    excel = FileExcelReader('SecB_RegisterAuthen_data.xlsx', 'Sheet1')

    test = TestRegAuth()
    test.setup_method()
    nRows = excel.getRowCount()
    for row in range(2, nRows + 1):
        flow = excel.readData(row,1)
        reason = excel.readData(row,2)
        address = excel.readData(row,3)
        expectedResult = excel.readData(row,4)

        if address is None:
            address = ""

            
        try:
            result = test.test_regauth(flow,reason,address,expectedResult)
            excel.writeData("Passed",row,5)
        except:
            excel.writeData("Failed",row,5)


    test.teardown_method()