# Generated by Selenium IDE
import openpyxl
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from selenium.common.exceptions import NoSuchElementException

class FileExcelReader:
    file = ""
    sheetName = ""

    def __init__(self, file, sheetName):
        self.file = file
        self.sheetName = sheetName

    def getRowCount(self):
        wordbook = openpyxl.load_workbook(self.file)
        sheet = wordbook[self.sheetName]
        return (sheet.max_row)

    def getColumnCount(self):
        wordbook = openpyxl.load_workbook(self.file)
        sheet = wordbook[self.sheetName]
        return (sheet.max_column)

    def readData(self, rownum, colnum):
        wordbook = openpyxl.load_workbook(self.file)
        sheet = wordbook[self.sheetName]
        return sheet.cell(row=rownum, column=colnum).value

    def writeData(self, data, rownum, colnum):
        wordbook = openpyxl.load_workbook(self.file)
        sheet = wordbook[self.sheetName]
        sheet.cell(row=rownum, column=colnum).value = data
        wordbook.save(self.file)

class TestLogin():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.driver.maximize_window()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
#   def check_exists_by_xpath(xpath):
#     try:
#         webdriver.find_element_by_xpath(xpath)
#     except NoSuchElementException:
#         return False
#     return True

  def test_login(self, username, password, expectedResult):
    self.driver.get('https://sso.hcmut.edu.vn/cas/login?service=https://mybk.hcmut.edu.vn/my/homeSSO.action')
    usernameInput = self.driver.find_element(By.NAME,"username")
    passwordInput = self.driver.find_element(By.NAME,"password")
    submitBtn = self.driver.find_element(By.NAME,"submit")
    usernameInput.send_keys(username)
    passwordInput.send_keys(password)    
    submitBtn.click()
    time.sleep(3)
    if expectedResult == "Success": #done
        assert self.driver.current_url == 'https://mybk.hcmut.edu.vn/my/homeSSO.action'
        logoutBtn = self.driver.find_element(By.XPATH,'/html/body/div[2]/div/div/div[2]/div/a[1]')
        logoutBtn.click()
        alert = self.driver.switch_to.alert
        time.sleep(1)
        alert.accept()
        time.sleep(1)
        loginPageBtn = self.driver.find_element(By.XPATH,'/html/body/div[2]/div/div/div[2]/div/a[1]')
        loginPageBtn.click()
        time.sleep(2)
        return True
    elif expectedResult == "InvalidAccount": #done
        errorNotification = self.driver.find_element(By.XPATH,'//*[@id="msg"]')
        assert errorNotification.text == "The credentials you provided cannot be determined to be authentic."
        return True
    elif expectedResult == "MissedUsername": #done
        errorNotification = self.driver.find_element(By.XPATH,'//*[@id="msg"]')
        assert errorNotification.text == "Please enter your username."
        return True
    elif expectedResult == "MissedPwd": #done
        errorNotification = self.driver.find_element(By.XPATH,'//*[@id="msg"]')
        assert errorNotification.text == "Please enter your password."
        return True
    else:        
        assert self.driver.find_element(By.XPATH,'//*[@id="msg"]')
        return True

        
    
  

if __name__ == "__main__":
    excel = FileExcelReader('SecB_login_data.xlsx', 'Sheet1')
    test = TestLogin()
    test.setup_method()
    nRows = excel.getRowCount()
    for row in range(2, nRows + 1):
        username = excel.readData(row,1)
        password = excel.readData(row,2)
        expectedResult = excel.readData(row,3)
        if username is None:
            username = ""
        if password is None:
            password = ""

        try:
            result = test.test_login(username, password, expectedResult)
            excel.writeData("Passed",row,4)
        except:
            excel.writeData("Failed",row,4)


    test.teardown_method()