# Generated by Selenium IDE
import openpyxl
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from selenium.common.exceptions import NoSuchElementException

class FileExcelReader:
    file = ""
    sheetName = ""

    def __init__(self, file, sheetName):
        self.file = file
        self.sheetName = sheetName

    def getRowCount(self):
        wordbook = openpyxl.load_workbook(self.file)
        sheet = wordbook[self.sheetName]
        return (sheet.max_row)

    def getColumnCount(self):
        wordbook = openpyxl.load_workbook(self.file)
        sheet = wordbook[self.sheetName]
        return (sheet.max_column)

    def readData(self, rownum, colnum):
        wordbook = openpyxl.load_workbook(self.file)
        sheet = wordbook[self.sheetName]
        return sheet.cell(row=rownum, column=colnum).value

    def writeData(self, data, rownum, colnum):
        wordbook = openpyxl.load_workbook(self.file)
        sheet = wordbook[self.sheetName]
        sheet.cell(row=rownum, column=colnum).value = data
        wordbook.save(self.file)

class TestChangePassword():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.driver.maximize_window()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
#   def check_exists_by_xpath(xpath):
#     try:
#         webdriver.find_element_by_xpath(xpath)
#     except NoSuchElementException:
#         return False
#     return True

  def test_changepassword(self, username, oldpassword,newpassword,confirmpassword, expectedResult):
    self.driver.get('https://account.hcmut.edu.vn/')
    usernameInp = self.driver.find_element(By.NAME,"login")
    oldpasswordInp = self.driver.find_element(By.NAME,"oldpassword")
    newpasswordInp = self.driver.find_element(By.NAME,"newpassword")
    confirmpasswordInp = self.driver.find_element(By.NAME,"confirmpassword")
    submitBtn = self.driver.find_element(By.XPATH,"/html/body/div/div/div/div[3]/form/div[5]/div/button")
    
    usernameInp.send_keys(username)
    oldpasswordInp.send_keys(oldpassword)
    newpasswordInp.send_keys(newpassword)
    confirmpasswordInp.send_keys(confirmpassword)

    submitBtn.click()
    time.sleep(2)
    if expectedResult == "Success":
        successAlert = self.driver.find_element(By.CLASS_NAME,'alert-success')
    elif expectedResult == "Invalid":        
        alertDanger = self.driver.find_element(By.CLASS_NAME,'alert-danger')
    elif expectedResult == "Warning":        
        alertWarning = self.driver.find_element(By.CLASS_NAME,'alert-warning')

        
    
  

if __name__ == "__main__":
    excel = FileExcelReader('SecB_changepass_data.xlsx', 'Sheet1')

    test = TestChangePassword()
    test.setup_method()
    nRows = excel.getRowCount()
    for row in range(2, nRows + 1):
        username = excel.readData(row,1)
        oldpassword = excel.readData(row,2)
        newpassword = excel.readData(row,3)
        confirmpassword = excel.readData(row,4)
        expectedResult = excel.readData(row,5)

        if username is None:
            username = ""
        if oldpassword is None:
            oldpassword = ""
        if newpassword is None:
            newpassword = ""
        if confirmpassword is None:
            confirmpassword = ""
            
        try:
            result = test.test_changepassword(username, oldpassword,newpassword,confirmpassword,expectedResult)
            excel.writeData("Passed",row,6)
        except:
            excel.writeData("Failed",row,6)


    test.teardown_method()